# Generated by Django 6.0.3 on 2026-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='type',
            field=models.CharField(choices=[('solo', 'Solo Artist'), ('band', 'Band'), ('dj', 'DJ'), ('other', 'Other')], default='solo', max_length=10),
        ),
    ]
