# Generated by Django 6.0.3 on 2026-04-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_artist_description_artist_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='type',
            new_name='artist_type',
        ),
    ]
